### ISSUE TITLE
Accept `<:Metric`

### ISSUE THREAD

**Issue by Datseris** [JuliaNeighbors/VPTrees.jl#1]
Instead of forcing all users of VPTrees to change a metric to a function, perhaps it is much easier to use multiple dispatch in this package only _once_, to allow both `Function` as well as `Metric` to be the input to `VPTree`. For example you can internally define `get_distance` or so like this:

```julia
get_distance(m::Metric, a, b) = evaluate(m, a, b)
get_distance(f::Function, a, b) = f(a, b)
```

This happens only once on the developers end, instead of an unlimited amount of times on the user end.

**Comment by altre** [comment]
Signature is now changed to accept  VPTree(data::Vector{InputType}, metric::Any; threaded=false), where metric can be any callable. This then includes Function and Metric, since StringDistances.jl and Distances.jl now both implement all evaluate as callables.
