### ISSUE TITLE
DataStructures  version

### ISSUE THREAD

**Issue by onetonfoot** [JuliaNeighbors/VPTrees.jl#13]
Hi, I think the versioning for `DataStructures ` is to lose if I run this with`DataStructures@0.17.20` 

```julia
data = [rand(2) for _ in 1:10000]
queries = [rand(2) for _ in 1:10]
k = 50
euclidean(x, y) = sqrt(sum((x .- y).^2))
vptree = VPTree(data, euclidean)
find_nearest(vptree, queries[1], k)
```

I get a method error 

```
MethodError: no method matching iterate(::DataStructures.BinaryHeap{Tuple{Float64,Int64},DataStructures.GreaterThan})
```

However, updating to `DataStructures@0.18` fixes it  I'm using `julia 1.5.1`.

**Comment by altre** [comment]
Thanks for reporting this, I'll look into it today.

**Comment by altre** [comment]
Prefered tighter lower bound over top() to prevent deprecation warning.
