### ISSUE TITLE
Incremental VPTree Building

### ISSUE THREAD

**Issue by MFaisalZaki** [JuliaNeighbors/VPTrees.jl#3]
Hello, 

I was wondering how we can have an incremental VPTree building; where I receive nodes like a data stream then locate its nearest neighbour then it will be its parent based on a given condition.

Best regards

**Comment by altre** [comment]
I would have to think about it more carefully to be sure, but I would have assumed that in most cases the datastructure will be less efficient if built dynamically.

A very simple way would be: insert the way you suggest and add a rebuild! method which rebuilds the VPTree after losing efficiency. 

There is this: http://www.dblab.ntua.gr/~gtsat/collection/dist-based%20indexing/NN-VPtree.ps
Which includes a method for inserts and deletes. However, their approach includes many optimizations not in this implementation.

@MFaisalZaki Why don't you try implementing something for this?
